### ISSUE TITLE
Can't build on arch linux.

### ISSUE THREAD

**Issue by jkbbwr** [hexagonal-sun/bic#1]
```
checking for ptrdiff_t... yes
./configure: line 13064: syntax error near unexpected token `,'
./configure: line 13064: `AX_CXX_COMPILE_STDCXX_11(, mandatory)'
```

**Comment by jetm** [comment]
I have created a [bic Arch Linux package](https://aur.archlinux.org/packages/bic/) in AUR

**Comment by andrewhodel** [comment]
You should include your shell log of making the package, so when bic has
released a new version and arch has changed slightly and you are no longer
concerned about it someone with less experience at package building can at
least get a handle on how they might approach it. They might even end up
updating or creating other dist packages and it is a one liner for you.
