### ISSUE TITLE
C-style comments not supported

### ISSUE THREAD

**Issue by tavianator** [hexagonal-sun/bic#10]
```
$ cat foo.c
/* Comment */
int main() {
    return 0;
}
$ ./src/bic foo.c
Parser Error: <stdin>:1 syntax error, unexpected '/'.
```

**Comment by hexagonal-sun** [comment]
Indeed, I'm going to look at making bic automatically preprocess C files that are input so macros are expanded, comments stripped, etc.

**Comment by vesche** [comment]
@hexagonal-sun 

In this same vein, support for define would be nice:

```
BIC> #define NUMBER 1337
Parser Error: syntax error, unexpected IDENTIFIER, expecting ',' or ';'.
```

**Comment by hexagonal-sun** [comment]
Ah good spot, I've raised a new issue for this as this is a REPL feature.

**Comment by hexagonal-sun** [comment]
This should now be fixed.  C files are now pass through the preprocessor before parsing.
