### ISSUE TITLE
`bic -l m`, cannot open library: Invalid ELF header

### ISSUE THREAD

**Issue by cjwelborn** [hexagonal-sun/bic#17]
Can't use the `sin()` function from `math.h`, because `libm` cannot be loaded.

```bash
bic -l m
```

Output:
```
Error: could not open library m: /usr/lib/x86_64-linux-gnu/libm.so: invalid ELF header
```

System Info:
```
Distro Information:
    Distributor ID      Ubuntu
    Description         Ubuntu 18.04.3 LTS
    Release             18.04
    Codename            bionic

Linux/Kernel Information:
    Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hexagonal-sun** [comment]
It looks like `/usr/lib/x86_64-linux-gnu/libm.so` is a linker script.  On my machine it points to `/usr/lib/libm.so.6`.  You can give bic a full path to a library in that case:
```
$ bic -l /usr/lib/libm.so.6
```
However, I'm getting:
```
BIC> #include <math.h>
Parser Error: <stdin>:315 syntax error, unexpected IDENTIFIER.
```
I'll look at fixing this.

**Comment by hexagonal-sun** [comment]
This should now be fixed:
```
$ ./src/bic -l /usr/lib/libm.so.6 
BIC> #include <math.h>
BIC> sin(0.5);
0.479426
```
Thanks for the report!

**Comment by cjwelborn** [comment]
@hexagonal-sun, that's awesome. Thank you. On my Ubuntu machine I actually have to do:

```bash
bic -l /lib/x86_64-linux-gnu/libm.so.6
```

..but after an `#include <math.h>` I can use everything. Thanks, `bic` is going to be very handy.

**Comment by hyphenrf** [comment]
Hello, this doesn't work on musl libc as it doesn't define lib-names.h (AFAIK)
