### ISSUE TITLE
segfault when trying to take a modulo

### ISSUE THREAD

**Issue by max6667** [hexagonal-sun/bic#18]
to replicate: 
```
BIC > int a;
BIC > a = 30 % 50;
Segmentation fault (core dumped)
```

i have attached the core dump
[coredump.tar.gz](https://github.com/hexagonal-sun/bic/files/3612575/coredump.tar.gz)

**Comment by hexagonal-sun** [comment]
Should now be fixed.  Looks like I forgot to implement this.  Thanks for the report!
