### ISSUE TITLE
Create a git tag, so github can generate a release

### ISSUE THREAD

**Issue by jetm** [hexagonal-sun/bic#21]
I want to create an Arch Linux package, but I will prefer a release to keep updating the package. When a tag is created, GitHub will generate tarballs.

**Comment by hexagonal-sun** [comment]
Good idea, I think it's probably due a release.

V 0.9.0 is out!

**Comment by hexagonal-sun** [comment]
@jetm  Thanks for creating the arch package, much appreciated!  I've just released v0.9.1 (don't worry it won't be this often normally).  Unfrotunetly, I was a little premature with the previous release - it had some pretty serious issues with the parser which should now be fixed.  If you could update the package, that would be great.

Thanks!

**Comment by jetm** [comment]
@hexagonal-sun Updated the Arch Linux package to v0.9.1. Don't worry in making all the changes are required. I will be updating the pkg in Arch Linux as soon as I can.
