### ISSUE TITLE
Bash syntax error in test.sh

### ISSUE THREAD

**Issue by bavier** [hexagonal-sun/bic#23]
The following line in `test.sh``:

https://github.com/hexagonal-sun/bic/blob/482ec540e56824a3da65fe807f8c89cd3a34deb1/testsuite/test.sh#L14

always produces a non-zero exit code, with the following output:

```
./test.sh: line 14: [: -x: binary operator expected
```
Replacing `-!` with `!` should fix the conditional.

**Comment by hexagonal-sun** [comment]
Nice catch - should now be fixed.  

Thanks for the report!
