### ISSUE TITLE
Mod result is wrong for negative numbers.

### ISSUE THREAD

**Issue by nilesr** [hexagonal-sun/bic#24]
Simplest way to reproduce:
```
$ bic -v
This is bic v0.9.1.

Enabled Features:

   tree-check: no
$ bic
(ins)BIC> -1 % 3;
2
(ins)BIC> ⏎
```

I installed this morning from the AUR. `cling`, `gcc` and `tcc` both agree that -1 % 3 should be -1.

```
[cling]$ -1 % 3
(int) -1
[cling]$ 
```

```
$ cat test.c
#include <stdio.h>
int main(int argc, char** argv) {
   printf("%d\n", -1 % 3);
}

$ make test
cc     test.c   -o test
$ ./test
-1
$ tcc -run test.c
-1
```

**Comment by hexagonal-sun** [comment]
Should now be fixed, looks like I was reading some old GNU MP documentation and ended up using the wrong function to calculate the remainder.

Thanks for the report!

**Comment by nilesr** [comment]
Thanks for the quick fix!
