### ISSUE TITLE
Failure when running `./configure`

### ISSUE THREAD

**Issue by flexibeast** [hexagonal-sun/bic#26]
Context: x86_64 Void Linux; bic commit 455ad8a9

After doing `autoreconf -i` and then running `./configure --enable-debug`, `configure` eventually fails with:

    checking for size_t... (cached) yes
    checking for uint16_t... yes
    checking for uint32_t... yes
    checking for uint8_t... yes
    checking for ptrdiff_t... yes
    ./configure: 17641: ./configure: Syntax error: word unexpected (expecting ")")

**Comment by hexagonal-sun** [comment]
Hmm, - that's strange.  Have you got autoconf-archive installed?  If not the M4 macros that I've used from there won't be expanded and could very well generate a syntax error.

**Comment by flexibeast** [comment]
Gah. \*embarrassed\* i'd somehow managed to miss installing autoconf-archive - my apologies! Sorry for wasting your time. Closing.
