### ISSUE TITLE
Is it possible to use bic as C frontend for a compiler?

### ISSUE THREAD

**Issue by dzavalishin** [hexagonal-sun/bic#27]
Hi.

I'm working on an OS based on a managed code. (Here is what is it: https://phantomdox.readthedocs.io/en/latest/)

Currently I have my own language compiler, but I'm looking for make Java and Python frontends for it.

I never thought of C as a possible language for such an environment, but now I do. :)

It there a point in your code where it is possible to extract AST and pass it to my compiler's backend for a code generation? I'd like to give it a try.

**Comment by hexagonal-sun** [comment]
Dmitry Zavalishin <notifications@github.com> writes:

> Hi.

Hi Dmitry,

> I'm working on an OS based on a managed code. (Here is what is it:
> https://phantomdox.readthedocs.io/en/latest/)

Very nice project!

> It there a point in your code where it is possible to extract AST and
> pass it to my compiler's backend for a code generation?

Absolutely, I've purposely tried to keep all AST generation code
separate from the evaluation for exactly this scenario.

If you pass bic a source file on the command line, for example `bic
test.c` it's parsed and the AST generated at: src/main.c:184.  If you
add the lines:

```
tree_dump(cfile_parse_head);
exit(0);
```

at
[this](https://github.com/hexagonal-sun/bic/blob/455ad8a9de0a9d6db865baa9bb3868825a5a76eb/src/main.c#L186)
point You can make bic dump the AST for files that have been parsed.

The `cfile_parse_head` reference is the head of the AST so that's what
you would need to pass to your codegen code.

If you take a look
[here](https://github.com/hexagonal-sun/bic#tree-objects) that should
provide some info on how to work with the AST.  You can also take a look
in src/evaluate.c for plenty of examples.

Regards,
-- 
Matt

**Comment by dzavalishin** [comment]
Thank you very much for a detailed answer! 
I will try it today.

**Comment by hexagonal-sun** [comment]
@dzavalishin Did you have any look using bic as a front-end?

**Comment by dzavalishin** [comment]
Failed 3 times attempting to autoconf it:
- cygwin is not supported
- win based ubuntu: failed
- real ubuntu: failed

checking for ptrdiff_t... yes
./configure: line 5705: syntax error near unexpected token `,'
./configure: line 5705: `AX_CXX_COMPILE_STDCXX_11(, mandatory)'

**Comment by hexagonal-sun** [comment]
I don't think you've got the `autoconf-archive` package installed.  Please re-install and re-run `autoreconf -i`.

**Comment by dzavalishin** [comment]
Thanx, you're right, I missed it 

Now I have:

make[4]: Entering directory '/home/dz/bic/src'
  CC       libbic_a-repl.o
repl.c:22:2: error: #error "No readline found"
 #error "No readline found"

**Comment by dzavalishin** [comment]
Tried 'sudo apt install libreadline-dev', now make is successful!

**Comment by dzavalishin** [comment]
I've added '-T' flag to dump AST after parsing. Now I have strange failure:

```
dz@Phantom-Ubuntu:~/bic$ ls
aclocal.m4      config.guess  config.h.in~   config.sub    depcomp     etc         main.ast     Makefile.in  src          testsuite
autom4te.cache  config.h      config.log     configure     doc         install-sh  Makefile     missing      stamp-h1     ylwrap
compile         config.h.in   config.status  configure.ac  Dockerfile  LICENSE     Makefile.am  README.org   test-driver
dz@Phantom-Ubuntu:~/bic$ bic -T src/main.c -I . 2>main.ast
```

Output in main.ast is:

```
src/main.c:3:10: fatal error: config.h: No such file or directory
 #include "config.h"
          ^~~~~~~~~~
compilation terminated.

<chain
  <tree T_DECL tDECL_OFFSET: 0
        tDECL_TYPE: 
    <tree T_TYPEDEF tTYPEDEF_EXP: 
      <tree D_T_ULONG>
    >
```

As you can see, there is config.h in current dir and I've added it to the search path too.

**Comment by dzavalishin** [comment]
Decided to start with a simplest .c src code. Got AST tree.

Am I right that tree node is `<tree TYPE_ID LEFT_TYPE_ID: LEFT [ RIGHT_TYPE_D: RIGHT ]>`?
So tree can have 1 or 2 children? 

(Seems that I'm wrong and it can have more children, as in T_FN_DEF)

Is it possible that chain contains subchain? Or just list of trees?

**Comment by hexagonal-sun** [comment]
Glad you got it working!

Indeed a tree can have zero or many children.  bic generates accessor macros for each tree type that is defined in `src/c.lang`. For example, to access the different parts of a for loop you could use:
```c
void print_for_loop(tree for_loop)
{
    tree_dump(tFLOOP_INIT(for_loop));
    tree_dump(tFLOOP_COND(for_loop));
    tree_dump(tFLOOP_AFTER(for_loop));
    tree_dump(tFLOOP_STMTS(for_loop));
}
```
This corresponds with the definition of the for loop type given in `src/c.lang:175`.

Hope that helps!

NOTE: code that does print out a for loop is autogenerated from the `c.lang` file (see `src/gendump.c`).

**Comment by dzavalishin** [comment]
My compiler is written in Java, so I can't use your C code to work with tree. Nevertheless, here is some progress on my side:

```
-Unconverted: chain
  -Unconverted: tree T_FN_DEF
    -Unconverted: tree T_IDENTIFIER
      +Node string const "main"
    -Unconverted: chain
      -Unconverted: tree T_DECL
        -Unconverted: chain
          -Unconverted: tree T_ASSIGN
            -Unconverted: tree T_IDENTIFIER
              +Node string const "i"
            +Node +
              +Node int const "10"
              +Node int const "5"
        +Node int const "0"
        -Unconverted: tree D_T_INT
      +Node return
        +Node int const "0"
    -Unconverted: chain
      -Unconverted: tree T_DECL
        -Unconverted: tree T_IDENTIFIER
          +Node string const "ac"
        +Node int const "0"
        -Unconverted: tree D_T_INT
      -Unconverted: tree T_DECL
        -Unconverted: tree T_POINTER
          -Unconverted: tree T_POINTER
            -Unconverted: tree T_IDENTIFIER
              +Node string const "av"
        +Node int const "0"
        -Unconverted: tree D_T_CHAR
    -Unconverted: tree D_T_INT
```

`+Node` is converted one.

I'm hesitating about how to implement C pointers in managed environment. I see 3 ways:

* Very C way (but incompatible with other languages): keep all C program state in a huge binary object - data segment. Easy, but pointless.
* Very object way - attempt to convert every C structure to object creating target system types as needed. Will break a lot of C code.
* Attempt to do a deep check if pointer is used in some C hacks such as converted to other pointer type, and if so - keep corresponding structure (or array of structs) in a binary container, letting to do any pointer ops on it. Best, but not easy to do.

**Comment by hexagonal-sun** [comment]
Hi @dzavalishin ,

I'm glad you've managed to make progress.  One note: i'm doing some refactoring of the parser at the moment so the AST for declarations *will* be changing. I wasn't parsing according to the standard and non-trivial declarations wouldn't parse.  See the bottom of #25 .

One feature that I've just added that you might be interested in is that bic can now dump out the AST in dot format.  If you use: `bic -TD <srcfile.c>` and run that through graphviz, you should have a nice graphical representation of the AST.

Regarding managed C pointers - I'm not too sure what the best solution is.  I know that with bic, if a program is invalid bic would crash just as a normal program would - bic doesn't update pointer refs and free references etc.  One problem that I can see, however you implement it, the language will allow you to get at any pointer you like.  For example what's to stop someone: `int foo = *((int *)0xdeadbeef);`?  All I can think is that you impose restrictions on what you can take an address of; it has to be an object that is in scope.

**Comment by hexagonal-sun** [comment]
Okay, I've now just finished the re-write of the parser in #33 and you'll be glad to know that the parser is now C11 compliant so it should parse *any* code that follows that standard.

Hope that helps!
