### ISSUE TITLE
Allow parsing source files with no main().

### ISSUE THREAD

**Issue by cjwelborn** [hexagonal-sun/bic#29]
I'm just following up on a comment I made in issue #16. Remove the `main` restriction on parsing C files, and ignore the first line of a file if it starts with `"#!"` (actually the shell may already remove this line on Linux. Edit: It doesn't, I checked). This opens up a whole new door for using pre-written functions, and allows C files to be "executed" with `bic` from the command line (`./myfile.c` would be opened by `bic`, which would parse and run the code).

Sorry, no pull request yet. I just wanted to put this idea on the list, in case anyone else was looking for an awesome feature to add to `bic`.

**Comment by dzavalishin** [comment]
Brilliant idea.

**Comment by cjwelborn** [comment]
I was kinda stopped in my tracks because of Issue #31. I can't get bic to evaluate a simple C file anymore (this is with a fresh checkout from master, and no changes yet).

**Comment by hexagonal-sun** [comment]
I've added some thoughts on this in #32 .

**Comment by hexagonal-sun** [comment]
#35 fixes this issue, closing.
