### ISSUE TITLE
Homebrew support/Formula

### ISSUE THREAD

**Issue by zbeekman** [hexagonal-sun/bic#38]
This is more a placeholder (feel free to assign the issue to me) to remind me to submit a formula to Homebrew/homebrew-core for `bic` once a stable `1.x` release is published.

In the meantime, if it is not too involved to convince `bic` to build with XCode's/macOS' native `bison` that would be ideal and make it very likely that the formula is accepted within hours or a day of submission.

If `bic` needs GNU Bison, and it is unreasonable or a huge effort to port it to use native macOS bison, a few words here in this issue explaining why will help move the submission along once it is submitted.

I have a formula written up that works with the current `master` branch, and the only audit failures are that there's no stable version yet (quickly and easily fixable with a 1.0 release) and a complaint about using GNU bison when macos provides bison. Porting to native bison or explaining why this is not desirable/possible is enough to dismiss that audit.

I'm including the formula [as an attachment](https://github.com/hexagonal-sun/bic/files/4189303/bic.rb.txt) and inline for future reference.

```ruby
class Bic < Formula
  desc "C interpreter and API explorer"
  homepage "https://github.com/hexagonal-sun/bic"
  head "https://github.com/hexagonal-sun/bic.git" # Needs url and sha256 inserted above this line on 1.0.0 release

  depends_on "autoconf" => :build
  depends_on "autoconf-archive" => :build
  depends_on "automake" => :build
  depends_on "bison" => :build # macOS bison is too outdated, build fails unless gnu bison is used
  depends_on "libtool" => :build if build.head?

  depends_on "gmp"
  depends_on "readline"

  uses_from_macos "flex" => :build

  def install
    system "autoreconf", "-fi" if build.head?
    system "./configure", "--disable-debug",
           "--disable-dependency-tracking",
          "--disable-silent-rules",
           "--prefix=#{prefix}"
    system "make", "install"
  end

  test do
    (testpath/"hello.c").write <<~EOS
      #include <stdio.h>
      int main () {
        puts("Hello Homebrew!");
      }
    EOS
    assert_equal "Hello Homebrew!", shell_output("#{bin}/bic -s hello.c").strip
  end
end
```

@hexagonal-sun Are you interested in me submitting a PR that would setup nightly (or CI) testing of `master` as homebrew builds it so that you can easily see if upstream changes (i.e., nightly tests when packages in Homebrew are upgraded) break `bic` or changes pushed to `master` break `bic`'s compatibility with Homebrew? I would use GH actions for this, I find it to be more reliable than Travis-CI for macOS stuff, and Homebrew and Github both use the same back-end provider (MacStadium) for Github actions (macOS) and Homebrew CI and binary compilation and distribution (a.k.a. "bottling").

**Comment by hexagonal-sun** [comment]
Many thanks for taking the time to write a formula for `bic`. The formula looks good, having said that I've *never* seen any ruby code before!

GNU Bison is only needed when _developing_ `bic` not for building from a distribution tarball. Homebrew essentially has two options for building:

- Git checkout: this would require bison as the source code for the parser is not included in the git repo and needs to be generated.
- Using the autotools distribution tarball: this would *not* require any bison to be installed as autotools distributes the generated source within the tarball. Users only need is a compiler.  Of course if the user then edits the parser then bison is required.

I'm not sure what Homebrew's preferred option is for autotools packages? If the latter option is used there is no dependency on any bison.  Nevertheless, I will see what I can accomplish with MacOS's native bison.

> Are you interested in me submitting a PR that would setup nightly (or CI) testing of master

Absolutely!  I rarely have access to a MacOS machine so having some better CI on the MacOS side of things would be really useful.

**Comment by zbeekman** [comment]
@hexagonal-sun 
> I'm not sure what Homebrew's preferred option is for autotools packages?

The prefered method is using a distribution tarball that would include the generated source files. If we assume Homebrew uses the autotools distribution tarball, can you please confirm for me that the following packages are not needed:

- `bison` ?
- `flex` ?
- `libtool` ?

What about `autoconf-archive`, is this needed for a autotools distribution tarball build?

> The formula looks good, having said that I've _never_ seen any ruby code before!

No worries! Homebrew creates a DSL of sorts so formulae are built with a limited subset of Ruby, plus the Homebrew DSL.

Just a heads up regarding autotools archive versus git checkout: This is exactly why I need to understand which tools are needed when building from an autotools release archive. Under normal circumstances only stable releases will be built and distributed as binaries and these will be built from the autotools release archive. However, there is no such release archive at this time for me to test with, which is where the
```
head "https://github.com/hexagonal-sun/bic.git" # Needs url and sha256 inserted above this line on 1.0.0 release
```
line comes into play. This lets me test and install `bic` without a release archive by cloning the default branch of the `bic` repository and users (or this project during nightly testing) can build and install the latest `bic` from source with `brew install --HEAD --fetch-HEAD --build-from-source bic` once the formula is added and accepted into homebrew. I just opened a PR on OpenBLAS to get them setup with nightly Homebrew testing because while trying to upgrade OpenBLAS in Homebrew I tripped over a build system bug they had. I would do something similar here for `bic` and probably also try to setup a more normal macOS CI pipeline too.

Please ping me this weekend to remind me as, I don't have time this week to look at this.

**Comment by hexagonal-sun** [comment]
@zbeekman 

> The prefered method is using a distribution tarball

In which case, `bison`, `flex`, `libtool` and `autoconf-archive` are *not* needed for building bic; they are all included as part of the distribution tarball. In theory, all that is needed to build the distribution tarball is a compiler.

> However, there is no such release archive at this time for me to test with

There is a distribution of the last release of `bic` that you could test [here](https://github.com/hexagonal-sun/bic/releases/download/v0.9.1/bic-v0.9.1.tar.gz). This was prior to many MacOS fixes,  so it may not work but I think it should compile.  In any case, I could provide you with a tarball of `master` if that would help?

If you wish to create a distribution from a git checkout, install the above tools, compile as normal then run `make dist`.  This will instructs autotools generate the necessary source code and produce the release tarball. The one caveat is that if the source code of the distribution is modified, some of the above tools may be required to regenerate the appropriate source, I'm presuming this won't be an issue in Homebrew's case.

If Homebrew does use `bic`'s relase tallball, does that mean we can relax the requirement of GNU `bison`?  I suppose if the formula doesn't list the apprpriate dependencies and relies on distribution tarballs, a user could run `brew install --HEAD --fetch-HEAD --build-from-source bic` which would fail?

> I just opened a PR on OpenBLAS to get them setup with nightly Homebrew testing

I'll take a look and try and familiarise myself with the PR, thanks!

**Comment by zbeekman** [comment]
Yes, the reason I want to sort the dependencies out is because my plan was to have the minimum required dependencies for building a release but condition the other dependencies on a build from git/source (I.e. `--HEAD`)

As far as bison goes: Yes, not needing bison for building a release tarball does mean that it’s even more likely to be OK to have a GNU bison dependency for the HEAD build. I’d say put porting to allow the source to be generated with Xcode’s bison on the back burner. The Homebrew CI process will still complain about it but, worst case scenario, we ditch the HEAD install. 

I wouldn’t bother looking at the OpenBLAS PR just yet. Let’s wait until the next release to worry about that. 

As far as testing goes, I can run make dist on master or try the older release, which, IIRC, built fine but failed tests on macOS. Even still this is good enough for testing purposes.

**Comment by hexagonal-sun** [comment]
Ah, I didn't realize you can have two sets of dependencies for a homebrew formula.  That should make things easier!  As you suggest, I'll put the bison investigation on the back-burner for now.

Given that, I've now just done `bic`'s first stable release! The distribution tarball is also available in the releases pages, so all that should be required for building is the compiler.  Let me know if you have any problems building the distribution tarball.

Once we've ironed out these issues, feel free to submit a PR for the formula to homebrew.

**Comment by zbeekman** [comment]
Here is the updated formula for the first stable release which includes the dependencies for building from source separately from the formula dependencies:

```ruby
class Bic < Formula
  desc "C interpreter and API explorer"
  homepage "https://github.com/hexagonal-sun/bic"
  url "https://github.com/hexagonal-sun/bic/releases/download/v1.0.0/bic-v1.0.0.tar.gz"
  sha256 "553324e39d87df59930d093a264c14176d5e3aaa24cd8bff276531fb94775100"
  head do
    url "https://github.com/hexagonal-sun/bic.git"

    depends_on "autoconf-archive" => :build
    depends_on "automake" => :build
    depends_on "bison" => :build # macOS bison is too outdated, build fails unless gnu bison is used
    depends_on "libtool" => :build if build.head?

    uses_from_macos "flex" => :build
  end

  depends_on "autoconf" => :build

  depends_on "gmp"
  depends_on "readline"

  def install
    system "autoreconf", "-fi" if build.head?
    system "./configure", "--disable-debug",
           "--disable-dependency-tracking",
          "--disable-silent-rules",
           "--prefix=#{prefix}"
    system "make", "install"
  end

  test do
    (testpath/"hello.c").write <<~EOS
      #include <stdio.h>
      int main () {
        puts("Hello Homebrew!");
      }
    EOS
    assert_equal "Hello Homebrew!", shell_output("#{bin}/bic -s hello.c").strip
  end
end
```

About to open a PR, and I'll link it here and close this issue once I have.

**Comment by zbeekman** [comment]
@hexagonal-sun 
> Once we've ironed out these issues, feel free to submit a PR for the formula to homebrew.

I didn't see/understand this last comment, so I've submitted a PR here: https://github.com/Homebrew/homebrew-core/pull/50534

What issues were you referring too?
