### ISSUE TITLE
failed to make on raspbian with raspberry 4

### ISSUE THREAD

**Issue by xueyuanl** [hexagonal-sun/bic#9]
the error message is:

`make  all-recursive`
`make[3]: Entering directory '/home/pi/workspace/bic/src'`
`Making all in armv7l`
`/bin/bash: line 20: cd: armv7l: No such file or directory`
`make[3]: *** [Makefile:938: all-recursive] Error 1`
`make[3]: Leaving directory '/home/pi/workspace/bic/src'`
`make[2]: *** [Makefile:478: all] Error 2`
`make[2]: Leaving directory '/home/pi/workspace/bic/src'`
`make[1]: *** [Makefile:409: all-recursive] Error 1`
`make[1]: Leaving directory '/home/pi/workspace/bic'`
`make: *** [Makefile:341: all] Error 2`

any idea? thanks!

**Comment by hexagonal-sun** [comment]
Unfortunately armv7 currently isn't supported, however this is something I'm going to be looking to add in the next few weeks.  For now, if you can get your pi working in aarch64 mode that should work.

**Comment by hexagonal-sun** [comment]
ARMv7 port added.  Please give it a try and let me know if you have any problems!
